### ISSUE TITLE
Add a proper exit mechanism to toolbar

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#19] opened 2013-11-01 16:27 UTC
Right now, closing the activity keeps it running in the background.  We need to follow the example set by other Sugar activities.

**Comment by LinkSlayer64** [comment] 2013-11-25 22:32
considered a duplicate of https://github.com/FOSSRIT/Sash/issues/18

**Closed as completed by LinkSlayer64** 2013-11-25 22:32 UTC
Labels: enhancement
